### PR TITLE
Hotfix timezone offset

### PR DESCRIPTION
**Pull request by brdrgz**
Fixes issues caused by https://github.com/activenetwork/actv/pull/43

### CODE REVIEW

**Comment by marvin-min** [comment]
@brdrgz Thanks for your effort on fixing my bug. Your functional code looks good. I think we need to merge master branch to this branch and fix the rspec problems(or add the test coverage).

**Comment by marvin-min** [comment]
@brdrgz I had added the rspec for the code changesand merge the master into this branch

**Comment by brdrgz** [comment]
I think ultimately this solution needs to be in A3, not ACTV (and not for all assets in those source systems, which is a very large set of assets), so this is probably the wrong way to approach the problem.

**Comment by brdrgz** [comment]
@marvin-min Also, just to add, the reason we reverted this was because it caused a lot of issues on production (500 errors, response time spikes).  A large number of camps / regecenter assets had a `timezoneOffset` of nil.

**Comment by marvin-min** [comment]
@brdrgz Thanks for you comments. I was also considering fix the issue at A3 side before the PR i had created in ACTV.There are 2 reasons that why i make the changes at ACTV at final:

1. We used the `registration_open_date` and `registration_close_date` many times in A3 code. If we parse the date with correct time zone at A3 side, we will call the `parse_date_with_correct_timezone` (just an example of the function to parse the date with correct timezone) function in each place where we using `registration_open_date` or `registration_close_date`. However,if we makes change at ACTV. we do not take care of this.

2.We add the default timezone 'UTC' at ACTV side now. If we want to correct the time zone at A3 side, we have to discard the 'UTC' timezone first and then add the correct. it looks strange.

**Pull request closed without merging**
